### ISSUE TITLE
missing models and PARSE ERROR: Argument: -m (--mode) Value 'noise_scale' does not meet constraint

### ISSUE THREAD

**Issue by idanka** [cmdrkotori/qtwaifu2x#2]
Hi!
Thx gui, but not works.
I use Fedora32, and install rpm

1. waifu2x-converter-cpp (DeadSix27)
2. qtwaifu2x

**missing models waifu2x directory (.waifu2x)**
sample: missing /home/user/.waifu2x/noise3_model.json￼
https://github.com/DeadSix27/waifu2x-converter-cpp/tree/master/models_rgb
- noise0_model.json
- noise1_model.json
- noise2_model.json
- noise3_model.json￼
- scale2.0x_model.json

**But original models dir and file:**
/usr/share/waifu2x-converter-cpp/noise0_model.json
/usr/share/waifu2x-converter-cpp/noise1_model.json
/usr/share/waifu2x-converter-cpp/noise2_model.json
/usr/share/waifu2x-converter-cpp/noise3_model.json
/usr/share/waifu2x-converter-cpp/scale2.0x_model.json

**Launching waifu2x PARSE ERROR: Argument: -m (--mode) Value '**noise_scale**' does not meet constraint: noise|scale|noise-scale Brief USAGE:**

Error argument... **realy argument: noise-scale**
Please correct it!

**Comment by eclipseo** [comment]
1) Do you have the latest version: qtwaifu2x-0-0.5.20200709git2973f6f.fc32
Please update to get the fix for input parameters.

2) The model are indeed located at /usr/share/waifu2x-converter-cpp/ I'm not sure why it is searching in /home/user/.waifu2x/
I'll investigate.

**Comment by idanka** [comment]
> 1. Do you have the latest version: qtwaifu2x-0-0.5.20200709git2973f6f.fc32
>    Please update to get the fix for input parameters.

Yes, i use this version
**dnf info  qtwaifu2x**
> Az utolsó metaadat lejárati ellenőrzés ennyi ideje volt: 0:00:27, ekkor: 2020. júl. 20., hétfő, 08:29:54 CEST.
> Telepített csomagok
> Név          : qtwaifu2x
> Verzió       : 0
> Kiadás       : **0.5.20200709git2973f6f.fc32**
> Architektúra : x86_64
> Méret        : 170 k
> Forrás       : qtwaifu2x-0-0.5.20200709git2973f6f.fc32.src.rpm
> Tároló       : @System
> Ezen tárolób : updates
> Összegzés    : Frontend for waifu2x-converter-cpp
> URL          : https://github.com/cmdrkotori/qtwaifu2x
> Licenc       : GPLv2
> Leírás       : Frontend for waifu2x-converter-cpp.

**Program arguments:**
> 	--scale-ratio 2.000 --noise-level 3 -m **noise_scale** -i /home/dankahazi/Pictures/fb/png/vf-Eaara1GUYAAZqYV_eredmény.png -o /home/dankahazi/Pictures/fb/png/vf-Eaara1GUYAAZqYV_eredmény_waifu2x_noise3_scale2.000.png --model-dir /home/dankahazi/.waifu2x
> 
> Launching waifu2x
> 
> PARSE ERROR: Argument: -m (--mode)
> 			 **Value 'noise_scale' does not meet constraint: noise|scale|noise-scale**

Thx!

**Comment by eclipseo** [comment]
Alright I have patched the source and pushed an update. It should be available in updates-testing within a couple of days: https://bodhi.fedoraproject.org/updates/FEDORA-2020-159897e22e

**Comment by eclipseo** [comment]
If it doesn't autodetect the models correctly, I suggest you force passing "/usr/share/waifu2x-converter-cpp/" directly.

It tries ~/waifu2x first, see if you do not have models remnant in there.

**Comment by idanka** [comment]
Thanks eclipseo!
