### ISSUE TITLE
-z,  --resume

### ISSUE THREAD

**Issue by idanka** [cmdrkotori/qtwaifu2x#4]
Pls add "resume" gui.
And missing -j options, sample: -j 4

waifu2x-converter-cpp  --help
....
   -z,  --resume
     Ignores files in input stream that have already been converted

 -j <integer>,  --jobs <integer>
     number of threads launching at the same time

Thx!

**Comment by cmdrkotori** [comment]
Done, but we didn't implement jobs because waifu2x will saturate the gpu with work.
